//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.24 at 11:57:35 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/ProductDetails", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.productdetails;
