//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.24 at 11:57:35 PM IST 
//


package org.example.productdetails;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;sequence>
     *     &lt;element name="productdetail" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *                 &lt;sequence>
 *                   &lt;element name="productid">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;pattern value="1.*"/>
 *                         &lt;length value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="productname">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z].*"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="productdescription">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z].*"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="accounttype">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="SavingsAccount"/>
 *                         &lt;enumeration value="CurrentAccount"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="productstatus">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Active"/>
 *                         &lt;enumeration value="Inactive"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>  
 *                   &lt;element name="validFrom">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                     	     &lt;pattern value="2[0-9]{3}-[01][0-9]-[0-3][0-9]"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>                 
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productdetail"
})
@XmlRootElement(name = "productdetails")
public class Productdetails {

	protected List<Productdetails.Productdetail> productdetail;

    /**
     * Gets the value of the productdetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productdetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCalldetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Productdetails.Productdetail }
     * 
     * 
     */
    public List<Productdetails.Productdetail> getProductdetails() {
        if (productdetail == null) {
        	productdetail = new ArrayList<Productdetails.Productdetail>();
        }
        return this.productdetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;sequence>
     *     &lt;element name="productdetail" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *                 &lt;sequence>
 *                   &lt;element name="productid">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;pattern value="1.*"/>
 *                         &lt;length value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="productname">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z].*"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="productdescription">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z].*"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="accounttype">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="SavingsAccount"/>
 *                         &lt;enumeration value="CurrentAccount"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="productstatus">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Active"/>
 *                         &lt;enumeration value="Inactive"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>  
 *                   &lt;element name="validFrom">
 *                    &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                     	     &lt;pattern value="2[0-9]{3}-[01][0-9]-[0-3][0-9]"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>                 
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productid",
        "productname",
        "productdescription",
        "accounttype",
        "productstatus",
        "validFrom"
    })

    
        public static class Productdetail {
    	
    	 @XmlElement(required = true)
         protected int productid;
 		@XmlElement(required = true)
         protected String productname;
         @XmlElement(required = true)
         protected String productdescription;
         @XmlElement(required = true)
         protected String accounttype;
         @XmlElement(required = true)
         protected String productstatus;
         @XmlElement(required = true)
         protected String validFrom;

         
         public int getproductid() {
             return productid;
         }

         
         public void setproductid(int value) {
             this.productid = value;
         }

         
         /**
          * Gets the value of the to property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getProductname() {
 			return productname;
 		}


         /**
          * Sets the value of the to property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setProductname(String productname) {
 			this.productname = productname;
 		}

         public String getProductdescription() {
 			return productdescription;
 		}

 		public void setProductdescription(String productdescription) {
 			this.productdescription = productdescription;
 		}

 		public String getAccounttype() {
 			return accounttype;
 		}

 		public void setAccounttype(String accounttype) {
 			this.accounttype = accounttype;
 		}

 		public String getProductstatus() {
 			return productstatus;
 		}

 		public void setProductstatus(String productstatus) {
 			this.productstatus = productstatus;
 		}

 		public String getValidFrom() {
 			return validFrom;
 		}

 		public void setValidFrom(String validFrom) {
 			this.validFrom = validFrom;
 		}



	}

}
